version: "3.7"

services:

  django:
    container_name: djangoproject
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - botnet
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "python django_app.py migrate &&
             python django_app.py createsuperuser --noinput || true &&
              python django_app.py loaddata fixtures/categories.json &&
             python django_app.py loaddata fixtures/products.json &&
             python django_app.py loaddata fixtures/banners.json &&
             python django_app.py runserver 0.0.0.0:8000"

  db:
    container_name: database
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    networks:
      - botnet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env


  tgbot:
    container_name: telegrambot
    build:
      context: .
    networks:
      - botnet
    restart: always
    env_file:
      - .env
    command: python app.py
    depends_on:
      - db
      - django

networks:
  botnet:
    driver: bridge

volumes:
  postgres_data: