# Generated by Django 5.1.4 on 2025-10-19 00:31

import django.core.validators
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0007_remove_product_description_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the banner', null=True, upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(help_text='Unique name for the banner', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='bannertranslation',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the banner', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='captcharecord',
            name='captcha',
            field=models.CharField(help_text='Captcha value', max_length=50),
        ),
        migrations.AlterField(
            model_name='captcharecord',
            name='is_passed',
            field=models.BooleanField(default=False, help_text='Indicates if the captcha was passed'),
        ),
        migrations.AlterField(
            model_name='captcharecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the captcha attempt'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of the product in the cart'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(help_text='Name of the category', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(help_text='Delivery address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(help_text='Name of the recipient', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', help_text='Status of the order', max_length=25),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the product at the time of order', max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of the product in the order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the product', null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=models.TextField(help_text='Description of the product', max_length=1024),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='name',
            field=models.CharField(help_text='Name of the product', max_length=150),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(help_text='First name of the user', max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', help_text='Preferred language of the user', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number of the user', max_length=128, region=None, unique=True, verbose_name='phone number'),
        ),
    ]
