# Generated by Django 5.1.4 on 2026-05-10 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0008_alter_banner_image_alter_banner_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='captcharecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='captcharecord',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='captcha', to='usersmanage.telegramuser'),
        ),
    ]
