# Generated by Django 5.1.4 on 2026-05-10 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0009_alter_captcharecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage, e.g. 15 for 15%', max_digits=5, verbose_name='Discount %')),
                ('valid_from', models.DateTimeField(verbose_name='Valid from')),
                ('valid_until', models.DateTimeField(verbose_name='Valid until')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited uses', null=True, verbose_name='Max uses')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Current uses')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount amount (USD)'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='usersmanage.promocode', verbose_name='Promo code'),
        ),
    ]
